name: wallet_app_prokit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.5.2
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^3.0.1

  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

  # Wallet App
  cached_network_image: ^3.2.0
  fl_chart: ^0.40.6
  otp_text_field: ^1.1.1
  dots_indicator: ^2.0.0
  scan: 1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7



flutter:

  uses-material-design: true

  assets:
   - images/walletApp/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

